import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    dir: 'ltr',
    appName: 'OIC',
    compliancePortal: 'Compliance Portal',
    searchPlaceholder: 'Search documents, audits, KB...',
    nav: {
      dashboard: 'Dashboard',
      documents: 'Documents',
      askCompliance: 'Ask Compliance',
      aiWriter: 'AI Writer',
      auditor: 'Auditor',
      templates: 'Templates',
      knowledgeBase: 'Knowledge Base',
      monitoring: 'Monitoring',
      analytics: 'Analytics',
      settings: 'Settings',
    },
    pages: {
      dashboard: 'Dashboard',
      documents: 'Documents',
      ask: 'Compliance Assistant',
      aiwriter: 'AI Writer',
      auditor: 'Auditor',
      templates: 'Templates',
      kb: 'Knowledge Base',
      monitoring: 'Monitoring',
      analytics: 'Analytics & Logs',
      settings: 'Settings',
    },
    docs: {
      allStatuses: 'All statuses',
      allTypes: 'All types',
      allFolders: 'All folders',
      allTags: 'All tags',
      lastEdited: 'Last edited',
      desc: 'Desc',
      trash: 'Trash',
      colTitle: 'Title',
      colType: 'Type',
      colStatus: 'Status',
      colOwner: 'Owner',
      colLastEdited: 'Last edited',
      colVer: 'Ver.',
      oicCategory: 'OIC Rules & Regulations',
      collapse: 'Collapse',
      expand: 'Expand',
      draft: 'Draft',
      reviewed: 'Reviewed',
      final: 'Final',
      rulesAndRegulation: 'Rules and Regulation',
      general: 'General',
      oicDocs: 'OIC Documents',
      policies: 'Policies',
      contracts: 'Contracts',
      compliance: 'Compliance',
      hr: 'HR',
      finance: 'Finance',
      safety: 'Safety',
      documentsWord: 'documents',
      noMatch: 'No documents match the selected filters.',
      noOicMatch: 'No OIC documents match the selected filters.',
    },
  },

  ar: {
    dir: 'rtl',
    appName: 'منظمة التعاون الإسلامي',
    compliancePortal: 'بوابة الامتثال',
    searchPlaceholder: 'البحث في المستندات والتدقيق...',
    nav: {
      dashboard: 'لوحة التحكم',
      documents: 'المستندات',
      askCompliance: 'استفسار الامتثال',
      aiWriter: 'الكاتب الذكي',
      auditor: 'المدقق',
      templates: 'القوالب',
      knowledgeBase: 'قاعدة المعرفة',
      monitoring: 'المراقبة',
      analytics: 'التحليلات',
      settings: 'الإعدادات',
    },
    pages: {
      dashboard: 'لوحة التحكم',
      documents: 'المستندات',
      ask: 'مساعد الامتثال',
      aiwriter: 'الكاتب الذكي',
      auditor: 'المدقق',
      templates: 'القوالب',
      kb: 'قاعدة المعرفة',
      monitoring: 'المراقبة',
      analytics: 'التحليلات والسجلات',
      settings: 'الإعدادات',
    },
    docs: {
      allStatuses: 'جميع الحالات',
      allTypes: 'جميع الأنواع',
      allFolders: 'جميع المجلدات',
      allTags: 'جميع العلامات',
      lastEdited: 'آخر تعديل',
      desc: 'تنازلي',
      trash: 'المهملات',
      colTitle: 'العنوان',
      colType: 'النوع',
      colStatus: 'الحالة',
      colOwner: 'المالك',
      colLastEdited: 'آخر تعديل',
      colVer: 'الإصدار',
      oicCategory: 'قواعد ولوائح منظمة التعاون الإسلامي',
      collapse: 'طي',
      expand: 'توسيع',
      draft: 'مسودة',
      reviewed: 'مراجعة',
      final: 'نهائي',
      rulesAndRegulation: 'القواعد واللوائح',
      general: 'عام',
      oicDocs: 'وثائق المنظمة',
      policies: 'السياسات',
      contracts: 'العقود',
      compliance: 'الامتثال',
      hr: 'الموارد البشرية',
      finance: 'المالية',
      safety: 'السلامة',
      documentsWord: 'مستندات',
      noMatch: 'لا توجد مستندات تطابق المرشحات المحددة.',
      noOicMatch: 'لا توجد وثائق تطابق المرشحات.',
    },
  },

  es: {
    dir: 'ltr',
    appName: 'OIC',
    compliancePortal: 'Portal de Cumplimiento',
    searchPlaceholder: 'Buscar documentos, auditorías...',
    nav: {
      dashboard: 'Panel de Control',
      documents: 'Documentos',
      askCompliance: 'Consultar Cumplimiento',
      aiWriter: 'Escritor IA',
      auditor: 'Auditor',
      templates: 'Plantillas',
      knowledgeBase: 'Base de Conocimiento',
      monitoring: 'Monitoreo',
      analytics: 'Analítica',
      settings: 'Configuración',
    },
    pages: {
      dashboard: 'Panel de Control',
      documents: 'Documentos',
      ask: 'Asistente de Cumplimiento',
      aiwriter: 'Escritor IA',
      auditor: 'Auditor',
      templates: 'Plantillas',
      kb: 'Base de Conocimiento',
      monitoring: 'Monitoreo',
      analytics: 'Analítica y Registros',
      settings: 'Configuración',
    },
    docs: {
      allStatuses: 'Todos los estados',
      allTypes: 'Todos los tipos',
      allFolders: 'Todas las carpetas',
      allTags: 'Todas las etiquetas',
      lastEdited: 'Último editado',
      desc: 'Desc',
      trash: 'Papelera',
      colTitle: 'Título',
      colType: 'Tipo',
      colStatus: 'Estado',
      colOwner: 'Propietario',
      colLastEdited: 'Último editado',
      colVer: 'Ver.',
      oicCategory: 'Reglas y Regulaciones OIC',
      collapse: 'Colapsar',
      expand: 'Expandir',
      draft: 'Borrador',
      reviewed: 'Revisado',
      final: 'Final',
      rulesAndRegulation: 'Reglas y Regulación',
      general: 'General',
      oicDocs: 'Documentos OIC',
      policies: 'Políticas',
      contracts: 'Contratos',
      compliance: 'Cumplimiento',
      hr: 'RRHH',
      finance: 'Finanzas',
      safety: 'Seguridad',
      documentsWord: 'documentos',
      noMatch: 'No hay documentos que coincidan con los filtros.',
      noOicMatch: 'No hay documentos OIC que coincidan.',
    },
  },
  // Add to translations object in src/context/LanguageContext.jsx
fr: {
    dir: 'ltr',
    appName: 'OCI',
    compliancePortal: 'Portail de Conformité',
    searchPlaceholder: 'Rechercher documents, audits...',
    nav: {
      dashboard: 'Tableau de Bord',
      documents: 'Documents',
      askCompliance: 'Assistant Conformité',
      aiWriter: 'Rédacteur IA',
      auditor: 'Auditeur',
      templates: 'Modèles',
      knowledgeBase: 'Base de Connaissances',
      monitoring: 'Surveillance',
      analytics: 'Analyses',
      settings: 'Paramètres',
    },
    pages: {
      dashboard: 'Tableau de Bord',
      documents: 'Documents',
      ask: 'Assistant Conformité',
      aiwriter: 'Rédacteur IA',
      auditor: 'Auditeur',
      templates: 'Modèles',
      kb: 'Base de Connaissances',
      monitoring: 'Surveillance',
      analytics: 'Analyses et Journaux',
      settings: 'Paramètres',
    },
    docs: {
      allStatuses: 'Tous les statuts',
      allTypes: 'Tous les types',
      allFolders: 'Tous les dossiers',
      allTags: 'Toutes les balises',
      lastEdited: 'Dernière modification',
      desc: 'Desc',
      trash: 'Corbeille',
      colTitle: 'Titre',
      colType: 'Type',
      colStatus: 'Statut',
      colOwner: 'Propriétaire',
      colLastEdited: 'Dernière modification',
      colVer: 'Ver.',
      oicCategory: 'Règles et Règlements OCI',
      collapse: 'Réduire',
      expand: 'Développer',
      draft: 'Brouillon',
      reviewed: 'Révisé',
      final: 'Final',
      rulesAndRegulation: 'Règles et Règlementation',
      general: 'Général',
      oicDocs: 'Documents OCI',
      policies: 'Politiques',
      contracts: 'Contrats',
      compliance: 'Conformité',
      hr: 'RH',
      finance: 'Finances',
      safety: 'Sécurité',
      documentsWord: 'documents',
      noMatch: 'Aucun document ne correspond aux filtres.',
      noOicMatch: 'Aucun document OCI ne correspond.',
    },
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');
  const t = translations[language];

  useEffect(() => {
    document.documentElement.dir = t.dir;
    document.documentElement.lang = language;
  }, [language, t.dir]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
